apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-worker
  template:
    metadata:
      labels:
        app: ai-worker
    spec:
      containers:
      - name: python-worker
        image: ai-worker:v1
        imagePullPolicy: Never
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: PYTHONUNBUFFERED
          value: "1"
