apiVersion: v1
kind: Service
metadata:
  name: redis-service       # Это имя будет использоваться как хост (адрес)
spec:
  selector:
    app: redis              # Сервис ищет Поды с такой же меткой из Deployment
  ports:
    - protocol: TCP
      port: 6379            # Порт СЕРВИСА (куда мы стучимся)
      targetPort: 6379      # Порт ВНУТРИ ПОДА (куда перенаправить трафик)
  type: ClusterIP           # Внутренний адрес, виден только внутри K8s